apiVersion: v1
kind: PersistentVolume
namespace: prometheus
metadata:
  name: prometheus-usb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/clusterfs/promdir"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-usb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi